const statuses=["Saved","Applied","Screening","Interview","Offer","Rejected"];
let apps=[];
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
async function load(){apps=await api("/api/applications");renderAll()}
function initials(s){return s.split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}
function badgeClass(s){return s.toLowerCase()}
function renderStats(){const active=apps.filter(a=>a.status!=="Rejected").length,interviews=apps.filter(a=>["Screening","Interview"].includes(a.status)).length,offers=apps.filter(a=>a.status==="Offer").length,responded=apps.filter(a=>!["Saved","Applied"].includes(a.status)).length;$("#activeStat").textContent=active;$("#interviewStat").textContent=interviews;$("#offerStat").textContent=offers;$("#responseStat").textContent=apps.length?Math.round(responded/apps.length*100)+"%":"0%";$("#weeklyCount").textContent=apps.length}
function renderPipeline(){const counts=Object.fromEntries(statuses.map(s=>[s,apps.filter(a=>a.status===s).length])),max=Math.max(1,...Object.values(counts));$("#pipeline").innerHTML=statuses.map(s=>'<div class="pipe-row"><span class="pipe-label">'+s+'</span><div class="pipe-track"><div style="width:'+counts[s]/max*100+'%"></div></div><b class="pipe-num">'+counts[s]+"</b></div>").join("")}
function actionList(items,el){if(!items.length){el.innerHTML='<div class="action"><strong>Nothing urgent.</strong><span>Add an application or follow-up to keep the pipeline moving.</span></div>';return}el.innerHTML=items.slice(0,4).map(a=>'<div class="action"><strong>'+a.nextAction||"Choose a next action"+' · '+a.company+'</strong><span>'+a.role+" · "+a.status+"</span></div>").join("")}
function appRow(a){return '<div class="app-row"><div class="company-logo">'+initials(a.company)+'</div><div class="app-main"><strong>'+a.company+'</strong><span>'+a.role+" · "+(a.location||"Location not set")+'</span></div><span class="badge '+badgeClass(a.status)+'">'+a.status+"</span></div>"}
function renderRecent(){const sorted=[...apps].sort((a,b)=>b.date.localeCompare(a.date));$("#recentList").innerHTML=sorted.slice(0,4).map(appRow).join("")||'<div class="empty">No applications yet.</div>'}
function renderNext(){actionList(apps.filter(a=>a.nextAction&&a.status!=="Rejected"),$("#nextActions"))}
function filtered(){const q=$("#searchInput").value.toLowerCase(),s=$("#statusFilter").value;return apps.filter(a=>(s==="all"||a.status===s)&&(!q||((a.company+" "+a.role).toLowerCase().includes(q))))}
function renderKanban(){const list=filtered();$("#resultCount").textContent=list.length+" application"+(list.length===1?"":"s");$("#kanban").innerHTML=statuses.map(s=>{const items=list.filter(a=>a.status===s);return '<div class="column"><div class="column-title"><span>'+s+"</span><b>"+items.length+"</b></div>"+(items.map(a=>'<div class="kan-card"><strong>'+a.company+'</strong><p>'+a.role+'</p><select data-id="'+a.id+'">'+statuses.map(x=>'<option '+(x===a.status?"selected":"")+'>'+x+"</option>").join("")+"</select></div>").join("")||'<div style="font-size:10px;color:#a0a8a0;padding:12px 4px">No applications</div>')+"</div>"}).join("");$$("#kanban select").forEach(sel=>sel.onchange=async()=>{await api("/api/applications/"+sel.dataset.id,{method:"PATCH",body:JSON.stringify({status:sel.value})});await load()})}
function renderInsights(){const counts=Object.fromEntries(statuses.map(s=>[s,apps.filter(a=>a.status===s).length])),top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0],due=apps.filter(a=>a.nextAction&&a.status!=="Rejected").length;$("#insightApps").textContent=apps.length;$("#insightStage").textContent=top?.[1]?top[0]:"—";$("#insightFollow").textContent=due;$("#insightHealth").textContent=apps.length>=5?"Active":"Getting started";$("#insightHeadline").textContent=apps.length>=5?"Your pipeline has enough activity to spot patterns.":"Build a little more pipeline.";$("#insightCopy").textContent=apps.length>=5?"Keep follow-ups visible and prioritize the next action with the highest leverage.":"Add a handful of real applications and this page becomes a useful weekly check-in for your search.";actionList(apps.filter(a=>a.nextAction&&a.status!=="Rejected"),$("#insightActions"))}
function renderAll(){renderStats();renderPipeline();renderRecent();renderNext();renderKanban();renderInsights()}
function switchView(view){$$(".view").forEach(x=>x.classList.add("hidden"));$("#"+view+"View").classList.remove("hidden");$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("#pageTitle").textContent=view[0].toUpperCase()+view.slice(1)}
$$(".nav-item").forEach(b=>b.onclick=()=>switchView(b.dataset.view));$$("[data-view-link]").forEach(b=>b.onclick=()=>switchView(b.dataset.viewLink));
$("#addTop").onclick=()=>{$("#modal").showModal();$("#applicationForm").reset();$("#applicationForm [name=date]").value=new Date().toISOString().slice(0,10)};$("#cancelModal").onclick=()=>$("#modal").close();
$("#applicationForm").onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.id=crypto.randomUUID();await api("/api/applications",{method:"POST",body:JSON.stringify(data)});$("#modal").close();await load();switchView("applications")};
$("#searchInput").oninput=renderKanban;$("#statusFilter").onchange=renderKanban;
$("#resetDemo").onclick=async()=>{if(confirm("Reset the demo applications?")){await api("/api/reset",{method:"POST"});await load()}};
load().catch(err=>{console.error(err);alert("Could not connect to the JobTrack backend.")});