const statuses=["Saved","Applied","Screening","Interview","Offer","Rejected"];
let apps=[];let currentMode="list";let selectedApplicationId=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
async function api(path,options={}){const r=await fetch(path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
function initials(s){return (s||"?").split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase()}
function badgeClass(s){return (s||"saved").toLowerCase()}
function formatDate(d){if(!d)return"Not set";return new Date(d+"T00:00:00").toLocaleDateString(undefined,{day:"2-digit",month:"short",year:"numeric"})}
async function load(){apps=await api("/api/applications");renderAll()}
function renderStats(){const active=apps.filter(a=>a.status!=="Rejected").length,interviews=apps.filter(a=>["Screening","Interview"].includes(a.status)).length,offers=apps.filter(a=>a.status==="Offer").length,responded=apps.filter(a=>!["Saved","Applied"].includes(a.status)).length;$("#activeStat").textContent=active;$("#interviewStat").textContent=interviews;$("#offerStat").textContent=offers;$("#responseStat").textContent=apps.length?Math.round(responded/apps.length*100)+"%":"0%";$("#weeklyCount").textContent=apps.length}
function renderPipeline(){const counts=Object.fromEntries(statuses.map(s=>[s,apps.filter(a=>a.status===s).length])),max=Math.max(1,...Object.values(counts));$("#pipeline").innerHTML=statuses.map(s=>'<div class="pipe-row"><span>'+s+'</span><div class="pipe-track"><div style="width:'+counts[s]/max*100+'%"></div></div><b>'+counts[s]+"</b></div>").join("")}
function actionList(items,el){if(!items.length){el.innerHTML='<div class="empty"><strong>Nothing here yet.</strong><br>Add an application and your next actions will appear here.</div>';return}el.innerHTML=items.slice(0,4).map(a=>'<div class="action"><strong>'+((a.nextAction||"Choose a next action"))+" · "+a.company+'</strong><span>'+a.role+" · "+a.status+"</span></div>").join("")}
function renderRecent(){const sorted=[...apps].sort((a,b)=>(b.date||"").localeCompare(a.date||""));$("#recentList").innerHTML=sorted.slice(0,4).map(a=>'<div class="action"><strong>'+a.company+" · "+a.role+'</strong><span>'+a.status+" · "+formatDate(a.date)+(a.salary?" · "+a.salary:"")+"</span></div>").join("")||'<div class="empty"><strong>Your pipeline is empty.</strong><br>Add your first application to start tracking your search.</div>'}
function filtered(){const q=$("#searchInput").value.toLowerCase(),s=$("#statusFilter").value;return apps.filter(a=>(s==="all"||a.status===s)&&(!q||((a.company+" "+a.role+" "+(a.location||"")).toLowerCase().includes(q))))}
function renderTable(){const list=filtered();$("#applicationCount").textContent=list.length+" application"+(list.length===1?"":"s");if(!list.length){$("#applicationTable").innerHTML='<div class="empty"><strong>No applications found.</strong><br>Try another filter or add a new application.</div>';$("#applicationDetail").innerHTML='<div class="detail-empty"><div class="detail-empty-icon">↗</div><h3>No application selected</h3><p>Add an application or change your filters to get started.</p></div>';return}$("#applicationTable").innerHTML=list.map(a=>'<article class="application-card '+(a.id===selectedApplicationId?"selected":"")+'" data-id="'+a.id+'"><div class="company-logo">'+initials(a.company)+'</div><div><h3>'+a.company+'</h3><p>'+a.role+(a.location?" · "+a.location:"")+'</p><div class="card-meta"><span>'+(a.salary||"Salary not set")+'</span><span>Applied '+formatDate(a.date)+'</span></div></div><div class="card-right"><span class="badge '+badgeClass(a.status)+'">'+a.status+'</span><time>'+formatDate(a.date)+'</time></div></article>').join("");$$(".application-card").forEach(c=>c.onclick=()=>selectApplication(c.dataset.id));if(!list.some(a=>a.id===selectedApplicationId))selectApplication(list[0].id);else renderDetail()}
function renderDetail(){const a=apps.find(x=>x.id===selectedApplicationId);if(!a)return;$("#applicationDetail").innerHTML='<div class="detail-header"><div class="detail-company"><div class="detail-logo">'+initials(a.company)+'</div><div><h2>'+a.company+'</h2><p>'+a.role+(a.location?" · "+a.location:"")+'</p></div></div><div class="detail-status"><span class="detail-label">Current stage</span><select id="detailStatus">'+statuses.map(s=>'<option '+(s===a.status?"selected":"")+">"+s+"</option>").join("")+'</select></div></div><div class="detail-grid"><div class="detail-field"><span class="detail-label">Salary</span><strong>'+(a.salary||"Not provided")+'</strong></div><div class="detail-field"><span class="detail-label">Applied</span><strong>'+formatDate(a.date)+'</strong></div><div class="detail-field"><span class="detail-label">Location</span><strong>'+(a.location||"Not provided")+'</strong></div></div><div class="detail-section"><span class="detail-label">Next action</span><div class="detail-next">'+(a.nextAction||"No next action set. Add one when you know what to do next.")+'</div></div><div class="detail-section"><h3>Job posting</h3>'+(a.url?'<a class="detail-link" href="'+a.url+'" target="_blank" rel="noopener">Open job posting ↗</a>':'<span class="cell-muted">No job URL saved.</span>')+'</div><div class="detail-section"><h3>Application record</h3><p class="cell-muted">Added on <strong>'+formatDate(a.date)+'</strong>. Current stage: <strong>'+a.status+'</strong>.</p></div>';$("#detailStatus").onchange=async()=>{await api("/api/applications/"+a.id,{method:"PATCH",body:JSON.stringify({status:$("#detailStatus").value})});await load()}}
function selectApplication(id){selectedApplicationId=id;renderTable()}
function renderKanban(){const list=filtered();$("#resultCount").textContent=list.length+" application"+(list.length===1?"":"s");$("#kanban").innerHTML=statuses.map(s=>{const items=list.filter(a=>a.status===s);return '<div class="column column-'+badgeClass(s)+'"><div class="column-title"><span>'+s+"</span><b>"+items.length+"</b></div>"+(items.map(a=>'<div class="kan-card"><strong>'+a.company+'</strong><p>'+a.role+'</p><p>'+formatDate(a.date)+(a.salary?" · "+a.salary:"")+'</p><select data-id="'+a.id+'">'+statuses.map(x=>'<option '+(x===a.status?"selected":"")+">"+x+"</option>").join("")+"</select></div>").join("")||'<div class="column-empty">No applications yet</div>')+"</div>"}).join("");$$("#kanban select").forEach(sel=>sel.onchange=async()=>{await api("/api/applications/"+sel.dataset.id,{method:"PATCH",body:JSON.stringify({status:sel.value})});await load()})}
function renderInsights(){const counts=Object.fromEntries(statuses.map(s=>[s,apps.filter(a=>a.status===s).length])),top=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0],due=apps.filter(a=>a.nextAction&&a.status!=="Rejected").length;$("#insightApps").textContent=apps.length;$("#insightStage").textContent=top?.[1]?top[0]:"—";$("#insightFollow").textContent=due;$("#insightHealth").textContent=apps.length>=5?"Active":apps.length?"Building":"Getting started";$("#insightHeadline").textContent=apps.length>=5?"Your pipeline has enough activity to spot patterns.":apps.length?"You're building momentum — keep the next action visible.":"Start by adding a few applications.";$("#insightCopy").textContent=apps.length?"A consistent next action turns a list of jobs into a manageable search workflow.":"Once you have activity in the pipeline, JobTrack will surface simple patterns to help you decide where to focus next.";actionList(apps.filter(a=>a.nextAction&&a.status!=="Rejected"),$("#insightActions"))}
function toggleMode(mode){currentMode=mode;$("#listMode").classList.toggle("hidden",mode!=="list");$("#boardMode").classList.toggle("hidden",mode!=="board");$$(".view-btn").forEach(b=>b.classList.toggle("active",b.dataset.mode===mode))}
function switchView(view){$$(".view").forEach(x=>x.classList.add("hidden"));$("#"+view+"View").classList.remove("hidden");$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===view));$("#pageTitle").textContent=view[0].toUpperCase()+view.slice(1)}
function openModal(){$("#modal").showModal();$("#applicationForm").reset();$("#applicationForm [name=date]").value=new Date().toISOString().slice(0,10)}
function renderAll(){renderStats();renderPipeline();renderRecent();actionList(apps.filter(a=>a.nextAction&&a.status!=="Rejected"),$("#nextActions"));renderTable();renderKanban();renderInsights();toggleMode(currentMode)}
$$(".nav-item").forEach(b=>b.onclick=()=>switchView(b.dataset.view));
$$("[data-view-link]").forEach(b=>b.onclick=()=>switchView(b.dataset.viewLink));
$$(".view-btn").forEach(b=>b.onclick=()=>toggleMode(b.dataset.mode));
$("#addTop").onclick=openModal;$("#addWelcome").onclick=openModal;$("#cancelModal").onclick=()=>$("#modal").close();
$("#applicationForm").onsubmit=async e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));data.id=crypto.randomUUID();await api("/api/applications",{method:"POST",body:JSON.stringify(data)});$("#modal").close();selectedApplicationId=data.id;await load();switchView("applications")};
$("#searchInput").oninput=()=>{renderTable();renderKanban()};$("#statusFilter").onchange=()=>{renderTable();renderKanban()};
$("#resetDemo").onclick=async()=>{if(confirm("Clear all applications from JobTrack? This cannot be undone.")){await api("/api/reset",{method:"POST"});selectedApplicationId=null;await load()}};
load().catch(err=>{console.error(err);alert("Could not connect to the JobTrack backend.")});